### ISSUE TITLE
CI says build not complete even though it was

### ISSUE THREAD

**Issue by ezeev** [earthly/cloud-issues#12]
A pipeline run today appeared to complete according to the Earthly logs in < 20 seconds but in CI it showed as still running for 16 minutes before ultimately completing. The logs were correct in this case as the build was competed in < 20 seconds and images were pushed. 

Here is the pipeline and commit:
https://github.com/earthly/earthly-solutions/commit/835f6891fda0645dc254b541056cb13815bf9009#diff-c6ef906b477330468a7c184ebd2d5f53663c699b32b4431b6724b00806b8ec75

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/15079807/226430517-993b3036-5939-49af-989e-dacfb1e0ac5b.png">

**Comment by ezeev** [comment]
Just ran into this again. The common denominator is it was the first run of the day. I assume something is out of synch during the wake up phase.
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/15079807/226668576-b149ef33-fd6b-444b-a9da-8d387a503249.png">

**Comment by mirho** [comment]
@ezeev This is actually a known issue. Its on my list to fix. Will bump it up

**Comment by mirho** [comment]
Closing this issue, as its been fixed. Added polling to the build detail page.
