### ISSUE TITLE
Unable to launch a satellite

### ISSUE THREAD

**Issue by gmpinder** [earthly/cloud-issues#23]
I setup my free account sometime this week and I haven't been able to launch any satellite. The `earthly` tool seems to know that I'm logged in. I can see my billing information and my orgs, but nothing to do with satellites.

```
$> earthly org ls
*  gmpinder    admin (personal)
   blue-build  admin
$> earthly sat launch test
Error: unable to authenticate: unauthorized
```

My `~/.earthly/` has an `auth.jwt` and I've created many tokens at this point, but still no luck. Help getting this sorted out would be super helpful.

**Comment by brandonSc** [comment]
Hi @gmpinder , what version of earthly are you using? There has been similar reports from other users on the v0.8 release, which we are still investigating. If you're on that version, could you try downgrading to [v0.7.23](https://github.com/earthly/earthly/releases/tag/v0.7.23)?

**Comment by gmpinder** [comment]
> Hi @gmpinder , what version of earthly are you using? There has been similar reports from other users on the v0.8 release, which we are still investigating. If you're on that version, could you try downgrading to [v0.7.23](https://github.com/earthly/earthly/releases/tag/v0.7.23)?

Yeah I'm on version 8. I'll try downgrading and see if that works

**Comment by gmpinder** [comment]
Ok so I got it working, but I had to delete everything in my `~/.earthly/` except my config and login again. Its now working on version 0.8.

**Comment by brandonSc** [comment]
Glad you got it working! And thanks for the clue in clearing the contents of `~/.earthly`. Whatever the issue is, it is only affecting a subset of users. We are trying to figure it out asap.

**Comment by gmpinder** [comment]
Yeah i have to do something similar in GitHub actions. I run the earthly setup at version 0.7, login and select the satellite, then run setup for 0.8 in order to use the satellites. Hope this info helps find the issue

**Comment by brandonSc** [comment]
We've identified the issue now, and created this separate ticket: https://github.com/earthly/earthly/issues/3761

What you're explaining I think makes sense, since v0.8 may not be creating a file that is required for authentication to work.  FYI @mikejholly
